import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '@/generated/prisma/client'
// This client is generated by Prisma.
// If TypeScript complains, ensure `generator client.output` matches this path
// and rerun `npx prisma generate`.

import { env } from "@/config/env";

const connectionString = `${env.DATABASE_URL}`

const adapter = new PrismaPg({ connectionString })
const prisma = new PrismaClient({ adapter })

export default prisma